/* eslint-disable */
// @generated by scripts/gen/gen_instrument_ids.py — DO NOT EDIT.
// Source of truth: crates/dsp/instruments.catalog.json
/** Engine-side instrument ids (crates/dsp kernels::Instrument). */
export const INST = {
  marimba: 0,
  vibraphone: 1,
  glockenspiel: 2,
  musicbox: 3,
  guitar: 4,
  bass: 5,
  epiano: 6,
  drums: 7,
  synthpad: 8,
  piano: 9,
  guitarSteel: 10,
  guitarElectric: 11,
  guitarDistorted: 12,
  drumsRock: 13,
  drumsJazz: 14,
  cello: 15,
  trombone: 16,
  violin: 17,
  viola: 18,
  contrabass: 19,
  trumpet: 20,
  frenchHorn: 21,
  saxophone: 22,
  organ: 23,
  xylophone: 24,
  tubularBells: 25,
  celesta: 26,
  harp: 27,
  pizzicato: 28,
} as const;

export type InstrumentId = (typeof INST)[keyof typeof INST];

/** Canonical public group names (plus aliases) accepted by the engine host. */
export type InstrumentGroup =
  | "marimba"
  | "mallet"
  | "vibraphone"
  | "glockenspiel"
  | "musicbox"
  | "guitar"
  | "bass"
  | "epiano"
  | "drums"
  | "synthpad"
  | "piano"
  | "drums-rock"
  | "drums-jazz"
  | "guitar-steel"
  | "guitar-electric"
  | "guitar-distorted"
  | "cello"
  | "trombone"
  | "violin"
  | "viola"
  | "contrabass"
  | "trumpet"
  | "frenchhorn"
  | "saxophone"
  | "organ"
  | "xylophone"
  | "tubularbells"
  | "celesta"
  | "harp"
  | "pizzicato"
  | "guitar-acoustic"
  | "guitar-acoustic-nylon"
  | "guitar-acoustic-steel"
  | "bass-electric"
  | "electric-bass"
  | "strings"
  | "brass"
  | "woodwind"
  | "voice"
  | "synth"
  | "percussion"
  | "unknown"
;

/** Group name → engine instrument id. */
export const GROUP_TO_INSTRUMENT: Record<InstrumentGroup, number> = {
  "marimba": INST.marimba,
  "mallet": INST.marimba,
  "vibraphone": INST.vibraphone,
  "glockenspiel": INST.glockenspiel,
  "musicbox": INST.musicbox,
  "guitar": INST.guitar,
  "bass": INST.bass,
  "epiano": INST.epiano,
  "drums": INST.drums,
  "synthpad": INST.synthpad,
  "piano": INST.piano,
  "drums-rock": INST.drumsRock,
  "drums-jazz": INST.drumsJazz,
  "guitar-steel": INST.guitarSteel,
  "guitar-electric": INST.guitarElectric,
  "guitar-distorted": INST.guitarDistorted,
  "cello": INST.cello,
  "trombone": INST.trombone,
  "violin": INST.violin,
  "viola": INST.viola,
  "contrabass": INST.contrabass,
  "trumpet": INST.trumpet,
  "frenchhorn": INST.frenchHorn,
  "saxophone": INST.saxophone,
  "organ": INST.organ,
  "xylophone": INST.xylophone,
  "tubularbells": INST.tubularBells,
  "celesta": INST.celesta,
  "harp": INST.harp,
  "pizzicato": INST.pizzicato,
  "guitar-acoustic": INST.guitar,
  "guitar-acoustic-nylon": INST.guitar,
  "guitar-acoustic-steel": INST.guitarSteel,
  "bass-electric": INST.bass,
  "electric-bass": INST.bass,
  "strings": INST.synthpad, // placeholder
  "brass": INST.trumpet,
  "woodwind": INST.organ, // placeholder
  "voice": INST.synthpad, // placeholder
  "synth": INST.synthpad,
  "percussion": INST.drums,
  "unknown": INST.marimba,
};

/** id → canonical key (for diagnostics / offline tools). */
export const INSTRUMENT_KEY_BY_ID: readonly string[] = [
  "marimba",
  "vibraphone",
  "glockenspiel",
  "musicbox",
  "guitar",
  "bass",
  "epiano",
  "drums",
  "synthpad",
  "piano",
  "guitar-steel",
  "guitar-electric",
  "guitar-distorted",
  "drums-rock",
  "drums-jazz",
  "cello",
  "trombone",
  "violin",
  "viola",
  "contrabass",
  "trumpet",
  "frenchhorn",
  "saxophone",
  "organ",
  "xylophone",
  "tubularbells",
  "celesta",
  "harp",
  "pizzicato",
];
